/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.IVistaMonitorDeCarrera;
import java.util.ArrayList;
import modelo.Apuesta;
import modelo.Carrera;
import modelo.Participante;

/**
 *
 * @author Mauro
 */
public class IUMonitorDeCarreras extends javax.swing.JFrame implements IVistaMonitorDeCarrera{

    /**
     * Creates new form IUMonitorDeCarreras
     */
    public IUMonitorDeCarreras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstApuestas = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstCarreras = new javax.swing.JList();
        btnCargar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstParticipantes = new javax.swing.JList();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(30, 20, 150, 30);

        jScrollPane1.setViewportView(lstApuestas);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(210, 220, 210, 130);

        jScrollPane2.setViewportView(lstCarreras);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(30, 70, 150, 130);

        btnCargar.setText("Cargar");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCargar);
        btnCargar.setBounds(210, 20, 65, 30);

        jScrollPane3.setViewportView(lstParticipantes);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(210, 70, 210, 130);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("INFO DE CARRERA"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 138, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 107, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 220, 150, 130);

        setBounds(0, 0, 471, 419);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCargarActionPerformed

    
    @Override
    public void cargarCarreras(ArrayList<Carrera> carreras) {
        ArrayList<String> lista = new ArrayList();
        for (Carrera c : carreras){
            lista.add(formatearCarrera(c));
        }
        lstCarreras.setListData(lista.toArray());
    }

    @Override
    public void cargarParticipantes(ArrayList<Participante> participantes) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void cargarApostadores(ArrayList<Apuesta> apuestas) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

      //Formatos para las listas propias de esta vista.
    private String formatearCarrera(Carrera carrera) {
        return carrera.getNumeroCarrera() + " - " + carrera.getEstado() + " - " + carrera.getNombre();
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargar;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList lstApuestas;
    private javax.swing.JList lstCarreras;
    private javax.swing.JList lstParticipantes;
    // End of variables declaration//GEN-END:variables
}
