/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Mauro
 */
public class IUMonitorDeCarreras extends javax.swing.JFrame {

    /**
     * Creates new form IUMonitorDeCarreras
     */
    public IUMonitorDeCarreras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstParticipantes = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstCarreras1 = new javax.swing.JList();
        btnCargar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstParticipantes1 = new javax.swing.JList();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jScrollPane1.setViewportView(lstParticipantes);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(210, 220, 210, 130);

        jScrollPane2.setViewportView(lstCarreras1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(30, 70, 150, 130);

        btnCargar.setText("Cargar");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCargar);
        btnCargar.setBounds(210, 20, 65, 30);

        jScrollPane3.setViewportView(lstParticipantes1);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(210, 70, 210, 130);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("INFO DE CARRERA"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 138, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 107, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 220, 150, 130);

        setBounds(0, 0, 471, 419);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        
    }//GEN-LAST:event_btnCargarActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList lstCarreras1;
    private javax.swing.JList lstParticipantes;
    private javax.swing.JList lstParticipantes1;
    // End of variables declaration//GEN-END:variables
}
