/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.util.Date;
import java.util.Timer;
import java.util.TimerTask;
import logica.Fachada;
import logica.Administrador;

/**
 *
 * @author Fernando
 */
public class BienvenidaAdministrador extends javax.swing.JDialog {

    Fachada logica = Fachada.getInstancia();
    /**
     * Creates new form BienvenidaAdministrador
     */
    public BienvenidaAdministrador(java.awt.Frame parent, boolean modal, Administrador adm) {
        super(parent, modal);
        initComponents();
        msjBienvenida.setText("Bienvenido " + adm.getNombreCompleto());
        Timer timer = new Timer();
        TimerTask tarea = new TimerTask() {
        @Override
        public void run() {
            //new MenuAdministrador(adm).setVisible(true);
            dispose();
        }
        };
        timer.schedule(tarea, 5000);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        msjBienvenida = new javax.swing.JLabel();
        aceptarMsj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        msjBienvenida.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        aceptarMsj.setText("Aceptar");
        aceptarMsj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarMsjActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(msjBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(aceptarMsj, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(msjBienvenida)
                .addGap(18, 18, 18)
                .addComponent(aceptarMsj)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarMsjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarMsjActionPerformed
        this.dispose();
    }//GEN-LAST:event_aceptarMsjActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarMsj;
    private javax.swing.JLabel msjBienvenida;
    // End of variables declaration//GEN-END:variables
}
