
package interfaz;

import java.text.DateFormat;
import java.util.ArrayList;
import java.util.Date;
import modelo.Caballo;
import modelo.Carrera;
import modelo.Fachada;
import modelo.Hipodromo;
import modelo.Jornada;
import modelo.Participante;


public class IUAbrirCarrera extends javax.swing.JFrame {
    
    Hipodromo seleccionado;
    Carrera carrera;
   
    /**
     * Creates new form IUAbrirCarrera
     */
    public IUAbrirCarrera(Hipodromo seleccionado) {
        initComponents();
        this.seleccionado = seleccionado;
        cargarCarrera();
        mostrarProximaCarrera();
        cargarParticipantes(carrera.getParticipantes());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstParticipantes = new javax.swing.JList();
        btnAbrirBoton = new javax.swing.JToggleButton();
        lblNumero = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(lstParticipantes);

        btnAbrirBoton.setText("Abrir");
        btnAbrirBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(btnAbrirBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 15, Short.MAX_VALUE)
                    .addComponent(lblNumero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAbrirBoton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAbrirBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirBotonActionPerformed
        carrera.abrir();
        this.dispose();
    }//GEN-LAST:event_btnAbrirBotonActionPerformed

    public void cargarCarrera(){
        Jornada jornada = seleccionado.buscarJornada(new Date());
        carrera = jornada.traerProximaCarrera();
    }
    
    public void mostrarProximaCarrera(){
           
        lblNumero.setText(Integer.toString(carrera.getNumeroCarrera()));
        lblNombre.setText(carrera.getNombre());
    }

    public ArrayList<String> convertirLista(ArrayList<Participante> aConvertir){
        
        ArrayList<String> lista = new ArrayList<String>();
        for (Participante p : aConvertir){
            lista.add("N°" + p.getNumero() + " - " + p.getNombreCaballo() + " - $"+ p.getDividendo());
        }
        
        return lista;
    }
    
    
    public void cargarParticipantes(ArrayList<Participante> participantes){
        
        ArrayList<String> stringParticipante = convertirLista(participantes);
        lstParticipantes.setListData(stringParticipante.toArray());
        
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAbrirBoton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JList lstParticipantes;
    // End of variables declaration//GEN-END:variables
}
