/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import logica.Administrador;
import logica.Fachada;
import logica.Hipodromo;
import logica.Jugador;

/**
 *
 * @author Mauro
 */
public class VentanaJugador extends javax.swing.JDialog {

    Fachada logica = Fachada.getInstancia();
    /**
     * Creates new form VentanaJugador
     */
    public VentanaJugador(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarHipodromos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstHipodromo = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstCarrera = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstCaballo = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnConfirmar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();

        jTextField3.setText("jTextField3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        lstHipodromo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lstHipodromo.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstHipodromoValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstHipodromo);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 90, 180, 160);

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel1.setText("HIPÓDROMO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 60, 150, 30);

        lstCarrera.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lstCarrera.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstCarreraValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstCarrera);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(240, 90, 180, 160);

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setText("CARRERA");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(240, 60, 150, 30);

        lstCaballo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jScrollPane3.setViewportView(lstCaballo);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(450, 90, 180, 160);

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setText("CABALLO");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(450, 60, 150, 30);

        jLabel4.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("¡Bienvenido! Lo invitamos a efectuar su apuesta...");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 20, 600, 20);

        txtMonto.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtMonto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoActionPerformed(evt);
            }
        });
        getContentPane().add(txtMonto);
        txtMonto.setBounds(340, 310, 100, 30);

        txtUsuario.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        getContentPane().add(txtUsuario);
        txtUsuario.setBounds(160, 400, 150, 30);

        txtPassword.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txtPassword);
        txtPassword.setBounds(160, 440, 150, 30);

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel5.setText("Monto de la apuesta:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(190, 310, 140, 30);

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("$");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(320, 310, 20, 30);

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel7.setText("Usuario");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(80, 400, 70, 30);

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel8.setText("Contraseña");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(80, 440, 70, 30);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(50, 370, 560, 10);

        btnConfirmar.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnConfirmar.setText("Confirmar Apuesta");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfirmar);
        btnConfirmar.setBounds(380, 400, 150, 30);

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 51));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Aquí podría ponerse la data del caballo seleccionado");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 264, 600, 30);

        btnCancelar.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(440, 440, 90, 30);

        setBounds(0, 0, 680, 542);
    }// </editor-fold>//GEN-END:initComponents

    private void txtMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        String nombreUsuario = txtUsuario.getText();
        String passUsuario = new String(txtPassword.getPassword());
        Jugador jugador = logica.loginJugador(nombreUsuario, passUsuario);
        if (jugador != null) {
            JOptionPane.showMessageDialog(this, "Apuesta realizada");
            limpiarFormulario();            
        } else {
            JOptionPane.showMessageDialog(this, "No se ha podido realizar su apuesta");
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void lstHipodromoValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstHipodromoValueChanged
        JOptionPane.showMessageDialog(this, lstHipodromo.getSelectedIndex());
        cargarCarreras(lstHipodromo.getSelectedIndex());
        
    }//GEN-LAST:event_lstHipodromoValueChanged

    private void lstCarreraValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstCarreraValueChanged
        JOptionPane.showMessageDialog(this, lstCarrera.getSelectedIndex());
        cargarParticipantes(lstCarrera.getSelectedIndex());
    }//GEN-LAST:event_lstCarreraValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaJugador dialog = new VentanaJugador(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JList<String> lstCaballo;
    private javax.swing.JList<String> lstCarrera;
    private javax.swing.JList lstHipodromo;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    private void cargarHipodromos() {
        ArrayList<Hipodromo> hipodromos = Fachada.getInstancia().getHipodromos();
        lstHipodromo.setListData(hipodromos.toArray());
    }
    
    private void cargarCarreras(int indexHipodromo){
        
    }
    
    private void cargarParticipantes(int indexCarrera){
        
    }
    
    private void limpiarFormulario(){
            lstHipodromo.removeAll();
            cargarHipodromos();
            lstCarrera.removeAll();
            lstCaballo.removeAll();
            txtMonto.setText("");
            txtUsuario.setText("");
            txtPassword.setText("");
    }
}
