/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import logica.Jugador;

/**
 *
 * @author Mauro
 */
public class VerSaldo extends javax.swing.JDialog {

    /**
     * Creates new form VerSaldo
     */
    public VerSaldo(java.awt.Frame parent, boolean modal, Jugador j) {
        super(parent, modal);
        initComponents();
        mostrarDatos(j);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombreFijo = new javax.swing.JLabel();
        lblSaldoFijo = new javax.swing.JLabel();
        lblUltimaApuestaFijo = new javax.swing.JLabel();
        lblNombreDinamico = new javax.swing.JLabel();
        lblSaldoDinamico = new javax.swing.JLabel();
        lblUltApuestaDinamico = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        lblNombreFijo.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        lblNombreFijo.setForeground(new java.awt.Color(204, 0, 0));
        lblNombreFijo.setText("Hola, ");
        getContentPane().add(lblNombreFijo);
        lblNombreFijo.setBounds(30, 50, 40, 30);

        lblSaldoFijo.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        lblSaldoFijo.setForeground(new java.awt.Color(204, 0, 0));
        lblSaldoFijo.setText("Su saldo disponible al momento es: ");
        getContentPane().add(lblSaldoFijo);
        lblSaldoFijo.setBounds(30, 90, 240, 30);

        lblUltimaApuestaFijo.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        lblUltimaApuestaFijo.setForeground(new java.awt.Color(204, 0, 0));
        lblUltimaApuestaFijo.setText("Última apuesta realizada:");
        getContentPane().add(lblUltimaApuestaFijo);
        lblUltimaApuestaFijo.setBounds(30, 130, 180, 30);

        lblNombreDinamico.setFont(new java.awt.Font("Calibri", 2, 16)); // NOI18N
        lblNombreDinamico.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(lblNombreDinamico);
        lblNombreDinamico.setBounds(70, 50, 190, 30);

        lblSaldoDinamico.setFont(new java.awt.Font("Calibri", 3, 16)); // NOI18N
        lblSaldoDinamico.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(lblSaldoDinamico);
        lblSaldoDinamico.setBounds(270, 90, 80, 30);

        lblUltApuestaDinamico.setFont(new java.awt.Font("Calibri", 3, 16)); // NOI18N
        lblUltApuestaDinamico.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(lblUltApuestaDinamico);
        lblUltApuestaDinamico.setBounds(50, 160, 290, 20);

        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(lblFecha);
        lblFecha.setBounds(204, 20, 170, 0);

        jButton1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(160, 230, 100, 30);

        setBounds(0, 0, 416, 327);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VerSaldo dialog = new VerSaldo(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblNombreDinamico;
    private javax.swing.JLabel lblNombreFijo;
    private javax.swing.JLabel lblSaldoDinamico;
    private javax.swing.JLabel lblSaldoFijo;
    private javax.swing.JLabel lblUltApuestaDinamico;
    private javax.swing.JLabel lblUltimaApuestaFijo;
    // End of variables declaration//GEN-END:variables

    private void mostrarDatos(Jugador j) {
        lblNombreDinamico.setText(j.getNombreCompleto());
        lblSaldoDinamico.setText("$ " +j.getSaldo());
        lblUltApuestaDinamico.setText("bla bla bla");
    }
}
